# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-XdxDph6iq6imGjJ4sLCZYwpunIN2Nd1
"""

# app.py

import streamlit as st
import graphviz

st.title("Diagram Creator")
st.write("Generate a diagram based on category definitions and levels.")

# User inputs
categories = st.text_area("Enter categories and levels (e.g., A -> B -> C)", height=200)
submit = st.button("Generate Diagram")

# Diagram generation
if submit:
    if categories.strip():
        graph = graphviz.Digraph(format="png")
        for line in categories.strip().split("\n"):
            levels = line.split("->")
            for i in range(len(levels) - 1):
                graph.edge(levels[i].strip(), levels[i + 1].strip())
        st.graphviz_chart(graph)

        # Save diagram with fixed size
        graph.attr(size="4.2,13.33")  # Set diagram size in inches
        graph.render("diagram", format="png", cleanup=True)
        st.image("diagram.png", caption="Generated Diagram", use_column_width=True)
    else:
        st.error("Please provide category definitions!")



